produccion/sami_v1.1/sami/urls.py
from django.contrib import admin
from django.urls import path
from simapp import views
from simapp import views as views_vista
from django.urls import include

urlpatterns = [
    #path('', views_vista.home, name="samiv1"),
    path('admin/', admin.site.urls),
    path('', include('simapp.urls')), #simulador-app:simapp
    #en adelante van las demas apps. Podrian ser diferentes a simuladores inalabricos.
]

produccion/sami_v1.1/simapp/urls.py
from django.urls import path
from . import views 

app_name='simapp'
urlpatterns = [
    #http://127.0.0.1:8000/ / 
    path('', views.home, name='presentacion_v1'),
    #
    #no se usan los formularios de fases, a pesar de que se pueda accesar a las rutas, no es posible guardar los parametros.
    #path('sim/', views.form_a1, name='sim_form_a1'),
    #path('sim/form_a2', views.form_a2, name='sim_form_a2'),
    #path('sim/form_a3', views.form_a3, name='sim_form_a3'),
    #path('sim/form_a4', views.form_a4, name='sim_form_a4'),
    #
    path('simulador/parametros', views.ver_parametros, name='lista_parametros'),
    #
    path('simulador/seleccionar_escenario', views.seleccionar_escenario, name="sim_form_escenarios"),
    #
    path('simulador/form_compacto', views.form_compacto, name='sim_form_compacto'),
    #
    #SI TIENE REDIRECT, DEBE TERMINAR EN /, DE LO CONTRARIO NO ES NECESARIO.
    #@redirect
    path('simulador/ejecutar_parametros/', views.ejecutar_parametros, name='parametros'),
    #simulador
    path('simulador/iniciar', views.iniciar_simulacion, name='iniciar_sim'),
    #
    path('resultados/simulacion-general', views.ver_presim, name='pre_sim'),
    path('resultados/simulacion', views.ver_sim, name='sim'),
    
    #path('simulador/tablas', views.ver_tablas, name='simulador_tablas'),
    #path('simulador/logs', views.ver_tablas, name='simulador_tablas'),
    path('estadisticas/seleccionar_comparacion', views.seleccionar_comparacion, name="sim_form_comparar_escenarios"),
    #@redirect
    path('estadisticas/resultados_comparacion/', views.resultados_comparacion, name="sim_resultados_comparacion_escenarios"),

    #auxiliar
    #path('extra/demo_sami_v1/', views.form_demo_sami_v1, name='demo_form_sami_v1'),
    path('extra/futuro/', views.futuro, name='futuro'),


]

produccion/sami_v1.1/simapp/models.py
from django.db import models

# Create your models here.

produccion/sami_v1.1/simapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
#form tools
from formtools.wizard.views import SessionWizardView
#
#
#fomularios simulador
from .forms import *
#from .forms import FormGeneral, FormPropagacion, FormBalanceAntenas,FormAsignacion
from .forms import FormSeleccion
from .forms import FormCompacto
from .forms import FormComparacion
#integracion simulador
import os
import json
#
import pyfiglet
#
#from .static.simulador import top_pruebas
print("From django.views:")
from .static.simulador import MAIN_simulador as samiv1
from .static.simulador.utilidades import config as cfg


#--------------------------------------
#--------------------------------------
'''Definiciones Globales'''
#--------------------------------------
#--------------------------------------

#--------------------------------------
#--------------------------------------
'''Definiciones Auxiliares'''
#--------------------------------------
#--------------------------------------
def convertir_str_2_bool(check):
    '''Convierte "True" o "False" a True o False'''
    res=False
    if check=="True":
        res=True
    else:
        pass
    return res


def validar_desvanecimiento(check):
    '''Valida el contenido de la variable desvanecimiento y ajusta los parametros'''
    flag=True
    if check=="False":
        flag=False
        tipo="none"
    else:
        flag=True
        tipo=check
    #print(flag,tipo)
    return flag, tipo



def configurar_vnfd(archivo_config):
    """Copia los archivos de configuración dado al archivo de configuracion local para ver sus parametros activos"""
    vnfd_sim=cfg.cargar_json(target_path="simapp/static/simulador/base_datos/vnfd_mapping")
    print("CONFIGURAR VNFD")
    print(archivo_config["cfg_simulador"]["params_general"]["iteracion"])
    print(vnfd_sim["cfg_simulador"]["params_general"]["Iteración"])
    

    vnfd_sim["cfg_simulador"]["params_general"]["Iteración"][0]=archivo_config["cfg_simulador"]["params_general"]["iteracion"]
    vnfd_sim["cfg_simulador"]["params_general"]["Número de celdas"][0]=archivo_config["cfg_simulador"]["params_general"]["n_celdas"]
    vnfd_sim["cfg_simulador"]["params_general"]["Portadora"][0]=archivo_config["cfg_simulador"]["params_general"]["portadora"][0]
    vnfd_sim["cfg_simulador"]["params_general"]["Distancia entre celdas"][0]=archivo_config["cfg_simulador"]["params_general"]["isd"]
    

    vnfd_sim["cfg_simulador"]["params_general"]["Geometría"][0]=archivo_config["cfg_simulador"]["params_general"]["geometria"]
    vnfd_sim["cfg_simulador"]["params_general"]["Radio de Celda"][0]=archivo_config["cfg_simulador"]["params_general"]["radio_cel"] 

    vnfd_sim["cfg_simulador"]["params_general"]["Distribución"][0]=archivo_config["cfg_simulador"]["params_general"]["distribucion"][0]
    vnfd_sim["cfg_simulador"]["params_general"]["Distribución"][1]=float(archivo_config["cfg_simulador"]["params_general"]["distribucion"][1])

    vnfd_sim["cfg_simulador"]["params_general"]["Imagen Potencia"][0]=archivo_config["cfg_simulador"]["params_general"]["imagen"]["resolucion"]
    #
    #
    vnfd_sim["cfg_simulador"]["params_propagacion"]["Modelo Pérdidas de Propagación"][0]=archivo_config["cfg_simulador"]["params_propagacion"]["modelo_perdidas"]
    vnfd_sim["cfg_simulador"]["params_propagacion"]["Parámetros Modelo"][0]=archivo_config["cfg_simulador"]["params_propagacion"]["params_modelo"]
    #[float(archivo_config["cfg_simulador"]["params_propagacion"]["mp1"]), float(archivo_config["cfg_simulador"]["params_general"]["mp2"]), float(archivo_config["cfg_simulador"]["params_general"]["mp3"]),float(archivo_config["cfg_simulador"]["params_general"]["mp4"])]


    flag_desv, tipo_desv=validar_desvanecimiento(archivo_config["cfg_simulador"]["params_propagacion"]["params_desv"])
    #print("check..",tipo_desv)
    vnfd_sim["cfg_simulador"]["params_propagacion"]["Desvanecimiento"][0]=tipo_desv["tipo"]
    vnfd_sim["cfg_simulador"]["params_propagacion"]["Parámetros desvanecimiento"][0]=archivo_config["cfg_simulador"]["params_propagacion"]["params_desv"]["params"]
    #[float(archivo_config["cfg_simulador"]["params_general"]["dp1"]),float(archivo_config["cfg_simulador"]["params_general"]["dp2"]),float(archivo_config["cfg_simulador"]["params_general"]["dp3"]),float(archivo_config["cfg_simulador"]["params_general"]["dp4"])]
    

    vnfd_sim["cfg_simulador"]["params_general"]["Figura de Ruido"][0]=float(archivo_config["cfg_simulador"]["params_general"]["nf"][0])
    vnfd_sim["cfg_simulador"]["params_general"]["Umbral SINR"][0]=float(archivo_config["cfg_simulador"]["params_general"]["ber_sinr"])
    #
    #
    print("views.py: potencias")
    vnfd_sim["cfg_simulador"]["params_balance"]["ptx"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["ptx"])
    vnfd_sim["cfg_simulador"]["params_balance"]["gtx"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["gtx"])
    vnfd_sim["cfg_simulador"]["params_balance"]["ltx"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["ltx"])
    vnfd_sim["cfg_simulador"]["params_balance"]["lrx"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["lrx"])
    vnfd_sim["cfg_simulador"]["params_balance"]["grx"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["grx"])
    #vnfd_sim["cfg_simulador"]["params_balance"]["sensibilidad"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["sensibilidad"])
    vnfd_sim["cfg_simulador"]["params_balance"]["mcl"][0]=float(archivo_config["cfg_simulador"]["params_balance"]["mcl"])
    #antenas
    vnfd_sim["cfg_simulador"]["params_antena"]["Tipo de Antena"][0]=archivo_config["cfg_simulador"]["params_antena"]["tipo"]
    vnfd_sim["cfg_simulador"]["params_antena"]["hpbw"][0]=archivo_config["cfg_simulador"]["params_antena"]["hpbw"]
    vnfd_sim["cfg_simulador"]["params_antena"]["Atenuación Mínima"][0]=float(archivo_config["cfg_simulador"]["params_antena"]["atmin"])
    #vnfd_sim["cfg_simulador"]["params_antena"]["apuntamiento"][0]=int(archivo_config["cfg_simulador"]["params_general"]["apuntamiento"])

    #
    #
    print("views.py: asignacion")
    vnfd_sim["cfg_simulador"]["params_asignacion"]["Tipo"][0]=archivo_config["cfg_simulador"]["params_asignacion"]["tipo"]
    vnfd_sim["cfg_simulador"]["params_asignacion"]["BW"][0]=int(archivo_config["cfg_simulador"]["params_asignacion"]["bw"][0])
    #config["cfg_simulador"]["params_asignacion"]["numerologia"]=float(archivo_config["cfg_simulador"]["params_asignacion"]["numerologia"])
    #config["cfg_simulador"]["params_asignacion"]["bw_guarda"][0]=int(archivo_config["cfg_simulador"]["params_asignacion"]["banda_guarda"])
    vnfd_sim["cfg_simulador"]["params_asignacion"]["Subportadora OFDM"][0]=float(archivo_config["cfg_simulador"]["params_asignacion"]["sub_ofdm"])
    vnfd_sim["cfg_simulador"]["params_asignacion"]["TRAMA OFDM"][0]=float(archivo_config["cfg_simulador"]["params_asignacion"]["trama_total"])
    vnfd_sim["cfg_simulador"]["params_asignacion"]["Símbolo OFDM DL"][0]=float(archivo_config["cfg_simulador"]["params_asignacion"]["simbolo_ofdm_dl"])
    vnfd_sim["cfg_simulador"]["params_asignacion"]["TRAMA OFDM"][0]=float(archivo_config["cfg_simulador"]["params_asignacion"]["frame"])

    
    #cfg.guardar_cfg(config, target_path="simapp/static/simulador/base_datos")
    cfg.guardar_json(vnfd_sim, target_path="simapp/static/simulador/base_datos/vnfd_mapping")
    print("vies.py")
    print(vnfd_sim)
    print(archivo_config)

#----------------------------END

#--------------------------------------
#--------------------------------------
'''VIEWs'''
#--------------------------------------
#--------------------------------------
# Create your views here.
def home(request):
    '''Index: debe cambiarse a la version del simulador mas reciente'''
    return render(request,'simapp/index/sami-index.html')


def form_demo_sami_v1(request):
    '''Demostracion de formulario.'''
    return render(request,'simapp/form_demo/sami-demo-v1.html')


def futuro(request):
    '''Para mostrar pagina bajo desarrollo'''
    return render(request,'simapp/sami-futuro.html')


def iniciar_simulacion(request):
    '''Inicia la simulacion''' 
    ascii_banner = pyfiglet.figlet_format("SAMI-5G")
    print(ascii_banner)
    cfg_sim=cfg.cargar_json(target_path="simapp/static/simulador/base_datos/config_sim")
    configuracion=cfg.cargar_json_full(target_path=cfg_sim["ruta_activa"])
    #configuracion=cfg.cargar_cfg(target_path="simapp/static/simulador/base_datos")
    if request.method == 'GET':
        try:
            arr = os.listdir()
            print(arr)
        except Exception as ex:
            print(ex)
        #exists = os.path.isfile('qw2ass<z/path/to/file')
        #print(exists)
        print("GET Metodo")
        
        '''***OPTIMIZACION***
        Anotacion de suma importancia:
        Que ocurre cuando el sistema es grande? es decir, con muchos usuarios y muchas celdas?
        La presimulacion se ejecuta como una simulacion y pierde el sentido de efectuarla. Esto
        ocurre debido a que la presimulacion y la simulacion ocurren al mismo tiempo. En la clase no existe
        ninguna diferencia entre ambas. La presimulacion si es diferente en simulador pues usa funciones internas
        configuradas con ese proposito, mas sin embargo la simulacion y todos los detalles tambien se ejecutan.
        
        Existen dos opciones para optimizar la presimulacion e indpendientemente ejecutar la simulacion que es el comportamiento esperado.
        La primera opcion directa y mas facil consiste en que al ejecutar la presimulacion, los datos para ese escenario (1 iteracion) se usen 
        para obtener estadisticas de muestras de valores (valores de potencia, sinr, estadisticas). Esta presimulacion seria la simulacion 0, cuya 
        utilidad puede o no (dependiendo del disenno) usarse en el compendio de simulacion montecarlo para su estudio. E

produccion/sami_v1.1/simapp/templates/simapp/resultados/sami-presim-graficas.html
{% extends 'base_sami.html' %}
{% load static %}
<!--
CUANDO SE CUMPLE LAS ITERACIONES MINIMAS, SE PUEDE EJECUTAR PRESIMULACION Y MONTECARLO
-->
{% block titulo_block %}
<a class="btn btn-info btn-xs" href="#">RESULTADOS DE SIMULACIÓN BÁSICA</a>
{% endblock %}


{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>¡Gráficas de Simulación Básica!</h4>
            <p class="mb-0">Los siguientes resultados de simulación básica (presimulación), se realizan sobre una muestra fija de distancia. Los demás parámetros son configurados de acuerdo a la configuración guardada por el usuario.</p>
            <hr>
            <a class="btn btn-info" href="{% url 'simapp:sim' %}">Siguiente</a>
             
        </div>
    </div>
</div>


<!--
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>¡Gráficas de Capacidad!</h4>
            <p class="mb-0">A continuación las gráficas. Si el simulador no ha concluido su ejecución, por favor recargar la página.</p>
        </div>
    </div>
</div>
-->
<div class="row">
    {% for key, value in img_disp.items %}
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ key }}</h4>
            </div>
            <div class="card-body">
                 
                <img src="{% static value %}" />
            </div>
        </div>
    </div>
    {% endfor %}

    
</div>

<hr>


{% endblock %}

produccion/sami_v1.1/simapp/templates/simapp/resultados/sami-sim-graficas-empty.html
{% extends 'base_sami.html' %}
{% load static %}
<!--
CUANDO NO SE CUMPLE LAS ITERACIONES MINIMAS, SE DEBE MOSTRAR UNA PAGINA QUE INDICA QUE NO SE PUEDE EJECUTAR MONTECARLO
-->
{% block titulo_block %}
<a class="btn btn-info btn-xs" href="#">RESULTADOS DE SIMULACIÓN DE MONTECARLO</a>
{% endblock %}


{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>¡Gráficas de Simulación de Montecarlo!</h4>
            <p class="mb-0">Los siguientes resultados de simulación, se realizan sobre una muestra aleatoria de usuarios distribuidos mediante el método de distribución correspondiente.</p>
            <hr>
            <a class="btn btn-warning" href="{% url 'simapp:lista_parametros' %}">Revisar configuraciones</a>
             
        </div>
    </div>
</div>


<!--
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>¡Gráficas de Capacidad!</h4>
            <p class="mb-0">A continuación las gráficas. Si el simulador no ha concluido su ejecución, por favor recargar la página.</p>
        </div>
    </div>
</div>
-->

<div class="row justify-content-center h-100 align-items-center">
    <div class="col-md-5">
        <div class="form-input-content text-center">
           
            <h1 class="error-text font-weight-bold">Realizaciones Insuficientes</h1>
            <h4 class="mt-4"><i class="fa fa-exclamation-triangle text-warning"></i> ¡No hay sufientes simulaciones!</h4>
            <p>Realiza 10 simulaciones o más para obtener gráficas.</p>
        </div>
    </div>
</div>


<hr>



{% endblock %}

produccion/sami_v1.1/simapp/templates/simapp/resultados/sami-sim-graficas.html
{% extends 'base_sami.html' %}
{% load static %}
<!--
RESULTADOS DE SIMULACION, PRESIMULACION.
-->
{% block titulo_block %}
<a class="btn btn-info btn-xs" href="#">RESULTADOS DE SIMULACIÓN DE MONTECARLO</a>
{% endblock %}


{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>¡Gráficas de Simulación de Montecarlo!</h4>
            <p class="mb-0">Los siguientes resultados de simulación, se realizan sobre una muestra aleatoria de usuarios distribuidos mediante el método de distribución correspondiente. Las estadísticas obtenidas se obtienen mediante el método de Montecarlo.</p>
            <hr>
            <a class="btn btn-info" href="{% url 'simapp:sim_form_comparar_escenarios' %}">Siguiente</a>
             
        </div>
    </div>
</div>


<!--
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>¡Gráficas de Capacidad!</h4>
            <p class="mb-0">A continuación las gráficas. Si el simulador no ha concluido su ejecución, por favor recargar la página.</p>
        </div>
    </div>
</div>
-->

<div class="row">
    {% for key, value in img_disp.items %}
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ key }}</h4>
            </div>
            <div class="card-body">
                 
                <img src="{% static value %}" />
            </div>
        </div>
    </div>
    {% endfor %}

    
</div>


<hr>



{% endblock %}